### ISSUE TITLE
User Story 2: High quality images and engaging descriptions (MUST HAVE)

### ISSUE THREAD

**Issue by j-mlo** [j-mlo/the-selah-duo#2]
As a Potential Client, I want to see high-quality images and engaging description of duo’s services and experience, so that I can decide whether I'd like them to book them for my event.

**Acceptance Criteria** 

- [x] The homepage features a carousel of high-quality pictures showing the duo playing at past events.
- [x] Feature a heading and eye-catching call to action button on the landing page.
- [x] Include 'About Me' section under the header with pictures of the members and engaging description of specialism.

**Tasks**

- [x] Add Bootstrap carousel featuring a number of ensemble's images.
- [x] Create a cover-text with a tag line and call to action button in the header.
- [x] Add 'About Me' section on the landing page with photos of members and profile description.
