### ISSUE TITLE
User Story 4: Enquiry form (MUST-HAVE)

### ISSUE THREAD

**Issue by j-mlo** [j-mlo/the-selah-duo#4]
As a party organiser I'd like to send an enquiry message to the duo to ask about booking them for a birthday party and need to easily find a contact form. 

**Acceptance Criteria**

- [x] A booking inquiry form for private events or game nights is easy to find, and the form is simple and easy to use. 
- [x] The form includes all necessary fields to gather event details: Name, Email, Phone Number, Event Type (Wedding,  Proposal, Birthday Party, Corporate, Baby Shower, Casual Soiree, Other) and Message. 
- [x] All fields on the form must be completed before the user can submit the form.
- [x] When the form is completed correctly, the user is taken to a thank you for enquiry page.

**Tasks**

- [x] Implement a booking inquiry form on the website.
- [x] Implement HTML validation on the form to fit the requirements above.
- [x] Create a thank you for enquiry page to direct users to after submitting the form.
