### ISSUE TITLE
User Story 5: Contact info and social links (MUST-HAVE)

### ISSUE THREAD

**Issue by j-mlo** [j-mlo/the-selah-duo#5]
As an affiliate venue, I need to easily find contact details and links to social media to verify the ensemble's credibility.

**Acceptance Criteria**

- [x] The website contains contact info (incl. email/postal address?) and links to social media in the footer.
- [x] This section is clearly visible and accessible from all parts of the website.

**Tasks**

- [x] Create a footer, which contains links to social media (openable in another tab) and simple contant info.
- [x] Ensure the contact section is clearly visible and accessible from all parts of the website, adhering to common design standards.
