### ISSUE TITLE
User Story 6: Pricing Information (MUST-HAVE)

### ISSUE THREAD

**Issue by j-mlo** [j-mlo/the-selah-duo#6]
As a wedding planner, I want to easily access pricing information/packages to be able to pass this onto my clients. 

**Acceptance Criteria** 

- [x] The website has a separate page dedicated to display pricing packages.
- [x] The page should be fully responsive and look good on different devices (using Bootstrap grid system).
- [x] Each price package card should display a name, description and price.

**Tasks**

- [x] Create a dedicated page with price packages cards for different services.
