### ISSUE TITLE
User Story 7: Testimonials (SHOULD-HAVE)

### ISSUE THREAD

**Issue by j-mlo** [j-mlo/the-selah-duo#7]
As a Prospective Customer, I want to read testimonials and reviews from other customers, so I can gauge the experiences of others and feel more confident about booking the music group for my event.

**Acceptance Criteria**

- [x] The website includes a section dedicated to displaying customer testimonials and reviews.
- [x] Testimonials are clearly visible and presented in a format that is easy to read and navigate.

**Tasks**

- [x] Create a static section on the website for customer testimonials.
- [x] Populate this section with a selection of pre-written testimonials.
