### ISSUE TITLE
User Story 8: Music List (COULD-HAVE)

### ISSUE THREAD

**Issue by j-mlo** [j-mlo/the-selah-duo#8]
As an engaged couple, I want to see a list of the group's set list, so that I know what songs they have available and confirm that my guests will like the music.

**Acceptance Criteria**

- [ ] The website has another section featuring a table list of the duo's set list. 

**Tasks**

- [ ] Add a table with a list of songs that band can perform. 
- [ ] The table features a scroll-bar to be able to easily navigate through it and not take up too much of the page.
